name: Docker build and push Staging

on:
  push:
    branches:
      - main
    paths:
      - "app/**"
      - ".github/workflows/docker-apply-staging.yml"

env: 
  AWS_REGION: ca-central-1
  REGISTRY: ${{ vars.STAGING_AWS_ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com/cds-superset-docs
  GITHUB_SHA: ${{ github.sha }}

permissions: {}

jobs:
  docker-push:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-24.04-arm
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
        DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
        DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
        DNS_PROXY_WILDCARDGREEDY: "true"

    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@e6de054238d6b7531b4efff3b6587d9aade6a06c # v6.2.3
      with:
        role-to-assume: arn:aws:iam::${{ vars.STAGING_AWS_ACCOUNT_ID }}:role/cds-superset-docs-docker-push
        role-session-name: PushContainer
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@03f1aad4c6c7ffd436567f42f9384779290529bd # v2.1.7 
  
    - name: Build container
      run: |
        docker build \
          --file ./app/Dockerfile \
          --platform linux/arm64 \
          --tag $REGISTRY:sha-${{ env.GITHUB_SHA }} \
          --tag $REGISTRY:latest ./app

    - name: Push Container to Amazon ECR
      run: |
        docker push $REGISTRY:sha-${{ env.GITHUB_SHA }}
        docker push $REGISTRY:latest

  docker-deploy:
    needs: docker-push
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/docker-deploy.yml
    with:
      aws_account_id: ${{ vars.STAGING_AWS_ACCOUNT_ID }}
      image_tag: sha-${{ github.sha }}
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

  docker-sbom:
    needs: docker-push
    permissions:
      contents: write
    uses: ./.github/workflows/docker-sbom-staging.yml
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

  notify-failure:
    if: failure()
    needs: [docker-push, docker-deploy, docker-sbom]
    uses: ./.github/workflows/workflow-failure.yml
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
      LOG_ANALYTICS_WORKSPACE_KEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.STAGING_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}
