name: Docker deploy Production

on:
  workflow_run:
    workflows: ["Docker build and push Production"]
    types:
    - completed

env: 
  AWS_REGION: ca-central-1
  FUNCTION_NAME: cds-superset-docs
  REGISTRY: ${{ vars.PROD_AWS_ACCOUNT_ID }}.dkr.ecr.ca-central-1.amazonaws.com/cds-superset-docs
  TAG_VERSION: ${{ github.event.workflow_run.head_branch }}

permissions:
  id-token: write

jobs:
  docker-deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@abae14dc37311af3a9bf8e6838dba2c1d873d06e
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
        DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

    - name: Configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        role-to-assume: arn:aws:iam::${{ vars.PROD_AWS_ACCOUNT_ID }}:role/cds-superset-docs-apply 
        role-session-name: UpdateLambda
        aws-region: ${{ env.AWS_REGION }}

    - name: Update Lambda
      run: |
        aws lambda update-function-code \
          --function-name ${{ env.FUNCTION_NAME }} \
          --image-uri $REGISTRY:$TAG_VERSION  > /dev/null 2>&1

