name: Docker SBOM Staging

on:
  workflow_call:
    secrets:
      LOG_ANALYTICS_WORKSPACE_ID:
        required: true
      LOG_ANALYTICS_WORKSPACE_KEY:
        required: true

permissions:
  contents: write

jobs:
  docker-sbom:
    runs-on: ubuntu-24.04-arm

    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@7b6ba63b4f045de61c98a3c1b99fdd08f32b0784 # v1.2.0
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: "${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}"
        DNS_PROXY_LOGANALYTICSSHAREDKEY: "${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}"
        DNS_PROXY_SAFELIST: "${{ vars.DNS_PROXY_SAFELIST }}"
        DNS_PROXY_WILDCARDGREEDY: "true"

    - name: Checkout
      uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0
      with:
        persist-credentials: false

    - name: Build image
      run: |
        docker build \
          --file ./app/Dockerfile \
          --platform linux/arm64 \
          --tag cds-superset-docs:latest ./app

    - name: Docker generate SBOM
      uses: cds-snc/security-tools/.github/actions/generate-sbom@d123fa2b895f7ef5b400fad333d2101b103b2e64 # v4.0.4
      env:
        TRIVY_DB_REPOSITORY: ${{ vars.TRIVY_DB_REPOSITORY }}
      with:
        docker_image: "cds-superset-docs:latest"
        dockerfile_path: "./app/Dockerfile"
        platform: "linux/arm64"
        token: "${{ secrets.GITHUB_TOKEN }}"
