name: Lambda restart Staging

on:
  workflow_dispatch:

env: 
  AWS_REGION: ca-central-1
  FUNCTION_NAME: cds-superset-docs

permissions:
  id-token: write

jobs:
  lambda-restart:
    runs-on: ubuntu-latest

    steps:
    - name: Audit DNS requests
      uses: cds-snc/dns-proxy-action@50d3033adea55c246f2e314920759cd81ecae522
      env:
        DNS_PROXY_FORWARDTOSENTINEL: "true"
        DNS_PROXY_LOGANALYTICSWORKSPACEID: ${{ secrets.LOG_ANALYTICS_WORKSPACE_ID }}
        DNS_PROXY_LOGANALYTICSSHAREDKEY: ${{ secrets.LOG_ANALYTICS_WORKSPACE_KEY }}

    - name: Configure aws credentials using OIDC
      uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a # v4.3.1
      with:
        role-to-assume: arn:aws:iam::${{ vars.STAGING_AWS_ACCOUNT_ID }}:role/cds-superset-docs-apply
        role-session-name: RestartLambda
        aws-region: ${{ env.AWS_REGION }}

    - name: Restart Lambda function
      run: |
        aws lambda update-function-configuration \
          --function-name ${{ env.FUNCTION_NAME }} \
          --description "Updated: $(date -u +'%Y-%m-%d %H:%M:%S UTC')" > /dev/null 2>&1

