name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@21cfef2b496dd8ef5b904c159339626a10ad380e # v1.11.6
        id: sre-app-token
        with:
          app-id: ${{ secrets.SRE_BOT_RW_APP_ID }}
          private-key: ${{ secrets.SRE_BOT_RW_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@5792afc6b46e9bb55deda9eda973a18c226bc3fc # v4.1.5
        with:
          token: ${{ steps.sre-app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
