name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@0d564482f06ca65fa9e77e2510873638c82206f2 # v1.11.5
        id: sre-app-token
        with:
          app-id: ${{ secrets.SRE_BOT_RW_APP_ID }}
          private-key: ${{ secrets.SRE_BOT_RW_PRIVATE_KEY }}

      - uses: googleapis/release-please-action@d1a8f221d7723166f48a584aebba00ef3f6febec # v4.1.4
        with:
          token: ${{ steps.sre-app-token.outputs.token }}
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
