name: Workflow failure

on:
  workflow_run:
    workflows:
      - "Docker build and push Production"
      - "Docker build and push Staging"
      - "Docker deploy Production"
      - "Docker deploy Staging"
      - "Terraform Apply Production"
      - "Terraform Apply Staging"
    types:
      - completed

permissions:
  contents: read

jobs:
  on-failure:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'failure'
    steps:
      - name: Determine target ops channel
        run: |
          WORKFLOW_NAME_LOWER="$(echo ${{ github.event.workflow_run.name }} | tr '[:upper:]' '[:lower:]')"
          if [[ "$WORKFLOW_NAME_LOWER" == *"staging"* ]]; then
            echo "SLACK_WEBHOOK_URL=${{ secrets.STAGING_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}" >> $GITHUB_ENV
          else
            echo "SLACK_WEBHOOK_URL=${{ secrets.PROD_CLOUDWATCH_ALERT_SLACK_WEBHOOK }}" >> $GITHUB_ENV
          fi

      - name: Notify Slack
        run: |
          json='{"blocks":[{"type":"section","text":{"type":"mrkdwn","text":":red: Superset Docs workflow failed: <${{ github.event.workflow_run.html_url }}|${{ github.event.workflow.name }}>"}}]}'
          curl -X POST -H 'Content-type: application/json' --data "$json" ${{ env.SLACK_WEBHOOK_URL }}
